### ISSUE TITLE
Project Dependencies Hint Path are Wrong

### ISSUE THREAD

**Issue by dol-leodagan** [Merec/DAoC-MapCreator#1]
Hello Merec,

There are some dependencies "Hint Path" not working "as is" in your project building...

In NifUtil.csproj lines 126,127

The reference for Magick.NET has a version instead of generic NuGet Package, and it targets a "libs" directory which is out of Git Tree... (should be something like ..\MapCreator\lib)

In NifUtil.csproj around lines 158 to 164, you check for SharpDX in a directory above Git Tree, so you need to call the git clone directory "MapCreator" for anything to work...

In MapCreator.csproj lines 516 to 518

There is a reference to a "filever.exe" binary, it's not included in git tree, and doesn't looks like it's needed to build the project...

**Comment by Merec** [comment]
I checkout out the project in a clean directory and fixed the problems, sorry for that.

The reason, why Magick.NET is added directly is simply its age. After I finished everything, the "All CPU" build has been released. There were many changes in handling color values and so on. Too much to handle at that point.

The project should run now in a clean directory after restoring the NuGet depencies. Is there a way to promt that there are unmet depencies?

**Comment by dol-leodagan** [comment]
I don't know about restoring NuGet dependencies, but your build message was pretty useful :)

With Latest git clone I have some error about 7z CLI missing I think...

**Comment by Merec** [comment]
I noticed, that missing NuGet depencies are automatically resolved when builing the first time.

Is everything working now?

**Comment by dol-leodagan** [comment]
Yes I had to launch nuget restore again for the 7z CLI ;)

It's now ready to launch with a fresh clone, nuget restore and rebuild !
